### PR TITLE
Upgrade to Laravel 11;

### PR DESCRIPTION
**Pull request by tralves**
Upgrades to Laravel 11. Everything works!
The only problem is that `croustibat/filament-jobs-monitor` is not updated yet, so I am using a patched version.

### CODE REVIEW

**Comment by tralves** [comment]
Ok. The patch was merged to `croustibat/filament-jobs-monitor` and the creator deleted the branch...
Unfortunately, we can't use the new version of `croustibat/filament-jobs-monitor` because [another PR introduced a different bug](https://github.com/croustibat/filament-jobs-monitor/pull/33#issuecomment-2021096923).

I'll update the PR when this issue gets figured out.

**Comment by Log1x** [comment]
hey, thanks for getting this started! i would like to also get the skeleton slimmed down to be parallel with Laravel 11. I can try to work on this in the next few days while that jobs monitor bug gets sorted.

**Comment by tralves** [comment]
Should be fixed now. Works here.

**Comment by tralves** [comment]
ah. Failed because Laravel requires PHP >= 8.2.

**Comment by Log1x** [comment]
no problem! should be able to work on this today

**Comment by Log1x** [comment]
should be good! let me know if you spot any issues.

**Pull request merged**
